version: '3.7'
services:
  mysql:
    image: mysql:8.0
    ports:
      - '3306:3306'
    volumes:
      - ./data:/var/lib/mysql
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=app
      - MYSQL_USER=app
      - MYSQL_PASSWORD=pass

  node:
    image: node:8
    user: "node"
    working_dir: /gate-simulator
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/home/node/app
    expose:
      - "9999"
    command:
      - "npm start"